<?php
/** 
 * Implements hook_menu()
 */
function qtest_menu() {
  $items = array();
  $items['qtest/form'] = array(
    'title' => 'My form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('qtest_add_form_page'),  
    'access arguments' => array('access content'),//access for all roles
    'description' => 'My form with form elements.',
    'modal'=> TRUE, //magic line 
    'type' => MENU_NORMAL_ITEM,
    'file' => 'qtest_form_element.inc',
  );
  return $items;
}
